name       : xfdesktop
version    : 4.18.1
release    : 1
source     :
    - https://archive.xfce.org/src/xfce/xfdesktop/4.18/xfdesktop-4.18.1.tar.bz2 : ef9268190c25877e22a9ff5aa31cc8ede120239cb0dfca080c174e7eed4ff756
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Xfce's desktop manager.
description: |
    Xfce's desktop manager.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(garcon-gtk3-1)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libxfconf-0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(thunarx-3)
setup      : |
    %configure --enable-thunarx --enable-notifications --disable-debug
build      : |
    %make
install    : |
    %make_install
